### ISSUE TITLE
pgAdmin 4 is unusable without PostgreSQL installation

### ISSUE THREAD

**Issue by IonMurzac** [romanmurzac/DrivenPath#20]
**Description:**
After installing pgAdmin 4 without PostgreSQL, the application couldn't be used, as it seemed to require a local PostgreSQL installation. This dependency was unexpected, as pgAdmin 4 should ideally allow connections to remote PostgreSQL servers without needing a local database setup.

**Steps to Reproduce:**

- Install pgAdmin 4 without PostgreSQL.
- Try to open and use pgAdmin 4.

**Expected Behavior:**
pgAdmin 4 should be able to start and allow users to connect to any PostgreSQL server, local or remote, without requiring a PostgreSQL installation on the same machine.

**Observed Behavior**:
pgAdmin 4 is unable to function until PostgreSQL is installed locally, even though the application is meant to manage databases on remote servers as well.

**Possible Solution**:
Provide clear guidance in the installation process about the dependency on PostgreSQL, or allow users to bypass this requirement if they intend to connect to remote PostgreSQL instances.

**Comment by romanmurzac** [comment]
Updated content and specified that PostgreSQL should be installed and only after the pgAdmin 4. Also, provided link to the PostgreSQL installation.
